// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEtxNfvOwqTdl85eLzkxid-X3vnfAxuc0',
    appId: '1:289864427664:web:daabd17957ea9389099015',
    messagingSenderId: '289864427664',
    projectId: 'auth-modul-c256b',
    authDomain: 'auth-modul-c256b.firebaseapp.com',
    storageBucket: 'auth-modul-c256b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO7P-O22LT05VcuyKlsPM2iuGWQ2DDOuQ',
    appId: '1:289864427664:android:e76d753fe362f31e099015',
    messagingSenderId: '289864427664',
    projectId: 'auth-modul-c256b',
    storageBucket: 'auth-modul-c256b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzER1-07mIAjUZwxiuGekir1BQbdJkSLk',
    appId: '1:289864427664:ios:52a1ba81f9f55dfe099015',
    messagingSenderId: '289864427664',
    projectId: 'auth-modul-c256b',
    storageBucket: 'auth-modul-c256b.firebasestorage.app',
    iosBundleId: 'com.example.fireauth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzER1-07mIAjUZwxiuGekir1BQbdJkSLk',
    appId: '1:289864427664:ios:52a1ba81f9f55dfe099015',
    messagingSenderId: '289864427664',
    projectId: 'auth-modul-c256b',
    storageBucket: 'auth-modul-c256b.firebasestorage.app',
    iosBundleId: 'com.example.fireauth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEtxNfvOwqTdl85eLzkxid-X3vnfAxuc0',
    appId: '1:289864427664:web:0b228ae53dbdfde6099015',
    messagingSenderId: '289864427664',
    projectId: 'auth-modul-c256b',
    authDomain: 'auth-modul-c256b.firebaseapp.com',
    storageBucket: 'auth-modul-c256b.firebasestorage.app',
  );
}
